/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables.records;


import com.skelril.skree.db.schema.tables.HighScores;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HighScoresRecord extends UpdatableRecordImpl<HighScoresRecord> implements Record4<Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = 905760642;

	/**
	 * Setter for <code>mc_db.high_scores.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mc_db.high_scores.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mc_db.high_scores.score_type_id</code>.
	 */
	public void setScoreTypeId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mc_db.high_scores.score_type_id</code>.
	 */
	public Integer getScoreTypeId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>mc_db.high_scores.player_id</code>.
	 */
	public void setPlayerId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mc_db.high_scores.player_id</code>.
	 */
	public Integer getPlayerId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mc_db.high_scores.value</code>.
	 */
	public void setValue(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mc_db.high_scores.value</code>.
	 */
	public Integer getValue() {
		return (Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Integer> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return HighScores.HIGH_SCORES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return HighScores.HIGH_SCORES.SCORE_TYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return HighScores.HIGH_SCORES.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return HighScores.HIGH_SCORES.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getScoreTypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HighScoresRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HighScoresRecord value2(Integer value) {
		setScoreTypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HighScoresRecord value3(Integer value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HighScoresRecord value4(Integer value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HighScoresRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HighScoresRecord
	 */
	public HighScoresRecord() {
		super(HighScores.HIGH_SCORES);
	}

	/**
	 * Create a detached, initialised HighScoresRecord
	 */
	public HighScoresRecord(Integer id, Integer scoreTypeId, Integer playerId, Integer value) {
		super(HighScores.HIGH_SCORES);

		setValue(0, id);
		setValue(1, scoreTypeId);
		setValue(2, playerId);
		setValue(3, value);
	}
}
