/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables.records;


import com.skelril.skree.db.schema.tables.ItemId;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemIdRecord extends UpdatableRecordImpl<ItemIdRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = -1679448121;

	/**
	 * Setter for <code>mc_db.item_id.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mc_db.item_id.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mc_db.item_id.mc_id</code>.
	 */
	public void setMcId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mc_db.item_id.mc_id</code>.
	 */
	public String getMcId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mc_db.item_id.variant</code>.
	 */
	public void setVariant(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mc_db.item_id.variant</code>.
	 */
	public String getVariant() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ItemId.ITEM_ID.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ItemId.ITEM_ID.MC_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return ItemId.ITEM_ID.VARIANT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getMcId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getVariant();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemIdRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemIdRecord value2(String value) {
		setMcId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemIdRecord value3(String value) {
		setVariant(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemIdRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemIdRecord
	 */
	public ItemIdRecord() {
		super(ItemId.ITEM_ID);
	}

	/**
	 * Create a detached, initialised ItemIdRecord
	 */
	public ItemIdRecord(Integer id, String mcId, String variant) {
		super(ItemId.ITEM_ID);

		setValue(0, id);
		setValue(1, mcId);
		setValue(2, variant);
	}
}
