/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables.records;


import com.skelril.skree.db.schema.tables.ItemAliases;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemAliasesRecord extends UpdatableRecordImpl<ItemAliasesRecord> implements Record3<Integer, String, Integer> {

	private static final long serialVersionUID = 666304745;

	/**
	 * Setter for <code>mc_db.item_aliases.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mc_db.item_aliases.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mc_db.item_aliases.alias</code>.
	 */
	public void setAlias(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mc_db.item_aliases.alias</code>.
	 */
	public String getAlias() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>mc_db.item_aliases.item_id</code>.
	 */
	public void setItemId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mc_db.item_aliases.item_id</code>.
	 */
	public Integer getItemId() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ItemAliases.ITEM_ALIASES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ItemAliases.ITEM_ALIASES.ALIAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return ItemAliases.ITEM_ALIASES.ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAlias();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemAliasesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemAliasesRecord value2(String value) {
		setAlias(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemAliasesRecord value3(Integer value) {
		setItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemAliasesRecord values(Integer value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemAliasesRecord
	 */
	public ItemAliasesRecord() {
		super(ItemAliases.ITEM_ALIASES);
	}

	/**
	 * Create a detached, initialised ItemAliasesRecord
	 */
	public ItemAliasesRecord(Integer id, String alias, Integer itemId) {
		super(ItemAliases.ITEM_ALIASES);

		setValue(0, id);
		setValue(1, alias);
		setValue(2, itemId);
	}
}
