/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables.records;


import com.skelril.skree.db.schema.tables.MarketTransactions;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketTransactionsRecord extends UpdatableRecordImpl<MarketTransactionsRecord> implements Record5<Integer, Integer, Integer, Integer, Timestamp> {

	private static final long serialVersionUID = -741028204;

	/**
	 * Setter for <code>mc_db.market_transactions.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mc_db.market_transactions.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mc_db.market_transactions.player_id</code>.
	 */
	public void setPlayerId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mc_db.market_transactions.player_id</code>.
	 */
	public Integer getPlayerId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>mc_db.market_transactions.item_id</code>.
	 */
	public void setItemId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mc_db.market_transactions.item_id</code>.
	 */
	public Integer getItemId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mc_db.market_transactions.quantity</code>.
	 */
	public void setQuantity(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mc_db.market_transactions.quantity</code>.
	 */
	public Integer getQuantity() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>mc_db.market_transactions.time</code>.
	 */
	public void setTime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mc_db.market_transactions.time</code>.
	 */
	public Timestamp getTime() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return MarketTransactions.MARKET_TRANSACTIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return MarketTransactions.MARKET_TRANSACTIONS.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return MarketTransactions.MARKET_TRANSACTIONS.ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return MarketTransactions.MARKET_TRANSACTIONS.QUANTITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return MarketTransactions.MARKET_TRANSACTIONS.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getQuantity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MarketTransactionsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MarketTransactionsRecord value2(Integer value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MarketTransactionsRecord value3(Integer value) {
		setItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MarketTransactionsRecord value4(Integer value) {
		setQuantity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MarketTransactionsRecord value5(Timestamp value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MarketTransactionsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MarketTransactionsRecord
	 */
	public MarketTransactionsRecord() {
		super(MarketTransactions.MARKET_TRANSACTIONS);
	}

	/**
	 * Create a detached, initialised MarketTransactionsRecord
	 */
	public MarketTransactionsRecord(Integer id, Integer playerId, Integer itemId, Integer quantity, Timestamp time) {
		super(MarketTransactions.MARKET_TRANSACTIONS);

		setValue(0, id);
		setValue(1, playerId);
		setValue(2, itemId);
		setValue(3, quantity);
		setValue(4, time);
	}
}
