/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables.records;


import com.skelril.skree.db.schema.tables.Portals;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PortalsRecord extends UpdatableRecordImpl<PortalsRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = 923036933;

	/**
	 * Setter for <code>mc_db.portals.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mc_db.portals.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>mc_db.portals.from_world_id</code>.
	 */
	public void setFromWorldId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mc_db.portals.from_world_id</code>.
	 */
	public Integer getFromWorldId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>mc_db.portals.player_id</code>.
	 */
	public void setPlayerId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mc_db.portals.player_id</code>.
	 */
	public Integer getPlayerId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>mc_db.portals.x</code>.
	 */
	public void setX(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mc_db.portals.x</code>.
	 */
	public Integer getX() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>mc_db.portals.y</code>.
	 */
	public void setY(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mc_db.portals.y</code>.
	 */
	public Integer getY() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>mc_db.portals.z</code>.
	 */
	public void setZ(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mc_db.portals.z</code>.
	 */
	public Integer getZ() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Portals.PORTALS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Portals.PORTALS.FROM_WORLD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Portals.PORTALS.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Portals.PORTALS.X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Portals.PORTALS.Y;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Portals.PORTALS.Z;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getFromWorldId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getY();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getZ();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord value2(Integer value) {
		setFromWorldId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord value3(Integer value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord value4(Integer value) {
		setX(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord value5(Integer value) {
		setY(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord value6(Integer value) {
		setZ(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PortalsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PortalsRecord
	 */
	public PortalsRecord() {
		super(Portals.PORTALS);
	}

	/**
	 * Create a detached, initialised PortalsRecord
	 */
	public PortalsRecord(Integer id, Integer fromWorldId, Integer playerId, Integer x, Integer y, Integer z) {
		super(Portals.PORTALS);

		setValue(0, id);
		setValue(1, fromWorldId);
		setValue(2, playerId);
		setValue(3, x);
		setValue(4, y);
		setValue(5, z);
	}
}
