/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables;


import com.skelril.skree.db.schema.Keys;
import com.skelril.skree.db.schema.McDb;
import com.skelril.skree.db.schema.tables.records.ItemAliasesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemAliases extends TableImpl<ItemAliasesRecord> {

	private static final long serialVersionUID = 438898148;

	/**
	 * The reference instance of <code>mc_db.item_aliases</code>
	 */
	public static final ItemAliases ITEM_ALIASES = new ItemAliases();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ItemAliasesRecord> getRecordType() {
		return ItemAliasesRecord.class;
	}

	/**
	 * The column <code>mc_db.item_aliases.id</code>.
	 */
	public final TableField<ItemAliasesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mc_db.item_aliases.alias</code>.
	 */
	public final TableField<ItemAliasesRecord, String> ALIAS = createField("alias", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>mc_db.item_aliases.item_id</code>.
	 */
	public final TableField<ItemAliasesRecord, Integer> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>mc_db.item_aliases</code> table reference
	 */
	public ItemAliases() {
		this("item_aliases", null);
	}

	/**
	 * Create an aliased <code>mc_db.item_aliases</code> table reference
	 */
	public ItemAliases(String alias) {
		this(alias, ITEM_ALIASES);
	}

	private ItemAliases(String alias, Table<ItemAliasesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ItemAliases(String alias, Table<ItemAliasesRecord> aliased, Field<?>[] parameters) {
		super(alias, McDb.MC_DB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ItemAliasesRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ITEM_ALIASES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ItemAliasesRecord> getPrimaryKey() {
		return Keys.KEY_ITEM_ALIASES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ItemAliasesRecord>> getKeys() {
		return Arrays.<UniqueKey<ItemAliasesRecord>>asList(Keys.KEY_ITEM_ALIASES_PRIMARY, Keys.KEY_ITEM_ALIASES_ALIAS_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ItemAliasesRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ItemAliasesRecord, ?>>asList(Keys.ITEM_ALIASES_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemAliases as(String alias) {
		return new ItemAliases(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ItemAliases rename(String name) {
		return new ItemAliases(name, null);
	}
}
