/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables;


import com.skelril.skree.db.schema.Keys;
import com.skelril.skree.db.schema.McDb;
import com.skelril.skree.db.schema.tables.records.ItemAliasesPrimaryRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemAliasesPrimary extends TableImpl<ItemAliasesPrimaryRecord> {

	private static final long serialVersionUID = 120425001;

	/**
	 * The reference instance of <code>mc_db.item_aliases_primary</code>
	 */
	public static final ItemAliasesPrimary ITEM_ALIASES_PRIMARY = new ItemAliasesPrimary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ItemAliasesPrimaryRecord> getRecordType() {
		return ItemAliasesPrimaryRecord.class;
	}

	/**
	 * The column <code>mc_db.item_aliases_primary.alias</code>.
	 */
	public final TableField<ItemAliasesPrimaryRecord, Integer> ALIAS = createField("alias", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>mc_db.item_aliases_primary</code> table reference
	 */
	public ItemAliasesPrimary() {
		this("item_aliases_primary", null);
	}

	/**
	 * Create an aliased <code>mc_db.item_aliases_primary</code> table reference
	 */
	public ItemAliasesPrimary(String alias) {
		this(alias, ITEM_ALIASES_PRIMARY);
	}

	private ItemAliasesPrimary(String alias, Table<ItemAliasesPrimaryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ItemAliasesPrimary(String alias, Table<ItemAliasesPrimaryRecord> aliased, Field<?>[] parameters) {
		super(alias, McDb.MC_DB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ItemAliasesPrimaryRecord> getPrimaryKey() {
		return Keys.KEY_ITEM_ALIASES_PRIMARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ItemAliasesPrimaryRecord>> getKeys() {
		return Arrays.<UniqueKey<ItemAliasesPrimaryRecord>>asList(Keys.KEY_ITEM_ALIASES_PRIMARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ItemAliasesPrimaryRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ItemAliasesPrimaryRecord, ?>>asList(Keys.FK_NEW_TABLE_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemAliasesPrimary as(String alias) {
		return new ItemAliasesPrimary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ItemAliasesPrimary rename(String name) {
		return new ItemAliasesPrimary(name, null);
	}
}
