/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables;


import com.skelril.skree.db.schema.Keys;
import com.skelril.skree.db.schema.McDb;
import com.skelril.skree.db.schema.tables.records.PlayersRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Players extends TableImpl<PlayersRecord> {

	private static final long serialVersionUID = 320218677;

	/**
	 * The reference instance of <code>mc_db.players</code>
	 */
	public static final Players PLAYERS = new Players();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PlayersRecord> getRecordType() {
		return PlayersRecord.class;
	}

	/**
	 * The column <code>mc_db.players.id</code>.
	 */
	public final TableField<PlayersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mc_db.players.uuid</code>.
	 */
	public final TableField<PlayersRecord, String> UUID = createField("uuid", org.jooq.impl.SQLDataType.CHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>mc_db.players.first_login</code>.
	 */
	public final TableField<PlayersRecord, Timestamp> FIRST_LOGIN = createField("first_login", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mc_db.players.last_login</code>.
	 */
	public final TableField<PlayersRecord, Timestamp> LAST_LOGIN = createField("last_login", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>mc_db.players.times_played</code>.
	 */
	public final TableField<PlayersRecord, Integer> TIMES_PLAYED = createField("times_played", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mc_db.players.seconds_played</code>.
	 */
	public final TableField<PlayersRecord, Integer> SECONDS_PLAYED = createField("seconds_played", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mc_db.players</code> table reference
	 */
	public Players() {
		this("players", null);
	}

	/**
	 * Create an aliased <code>mc_db.players</code> table reference
	 */
	public Players(String alias) {
		this(alias, PLAYERS);
	}

	private Players(String alias, Table<PlayersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Players(String alias, Table<PlayersRecord> aliased, Field<?>[] parameters) {
		super(alias, McDb.MC_DB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PlayersRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PLAYERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PlayersRecord> getPrimaryKey() {
		return Keys.KEY_PLAYERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PlayersRecord>> getKeys() {
		return Arrays.<UniqueKey<PlayersRecord>>asList(Keys.KEY_PLAYERS_PRIMARY, Keys.KEY_PLAYERS_UUID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Players as(String alias) {
		return new Players(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Players rename(String name) {
		return new Players(name, null);
	}
}
