/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema.tables;


import com.skelril.skree.db.schema.Keys;
import com.skelril.skree.db.schema.McDb;
import com.skelril.skree.db.schema.tables.records.RegionMembersRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegionMembers extends TableImpl<RegionMembersRecord> {

	private static final long serialVersionUID = 1843664932;

	/**
	 * The reference instance of <code>mc_db.region_members</code>
	 */
	public static final RegionMembers REGION_MEMBERS = new RegionMembers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RegionMembersRecord> getRecordType() {
		return RegionMembersRecord.class;
	}

	/**
	 * The column <code>mc_db.region_members.id</code>.
	 */
	public final TableField<RegionMembersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mc_db.region_members.region_id</code>.
	 */
	public final TableField<RegionMembersRecord, Integer> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>mc_db.region_members.player_id</code>.
	 */
	public final TableField<RegionMembersRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>mc_db.region_members</code> table reference
	 */
	public RegionMembers() {
		this("region_members", null);
	}

	/**
	 * Create an aliased <code>mc_db.region_members</code> table reference
	 */
	public RegionMembers(String alias) {
		this(alias, REGION_MEMBERS);
	}

	private RegionMembers(String alias, Table<RegionMembersRecord> aliased) {
		this(alias, aliased, null);
	}

	private RegionMembers(String alias, Table<RegionMembersRecord> aliased, Field<?>[] parameters) {
		super(alias, McDb.MC_DB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RegionMembersRecord, Integer> getIdentity() {
		return Keys.IDENTITY_REGION_MEMBERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RegionMembersRecord> getPrimaryKey() {
		return Keys.KEY_REGION_MEMBERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RegionMembersRecord>> getKeys() {
		return Arrays.<UniqueKey<RegionMembersRecord>>asList(Keys.KEY_REGION_MEMBERS_PRIMARY, Keys.KEY_REGION_MEMBERS_REGION_PLAYER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RegionMembersRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RegionMembersRecord, ?>>asList(Keys.FK_REGION, Keys.FK_PLAYER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RegionMembers as(String alias) {
		return new RegionMembers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RegionMembers rename(String name) {
		return new RegionMembers(name, null);
	}
}
