/**
 * This class is generated by jOOQ
 */
package com.skelril.skree.db.schema;


import com.skelril.skree.db.schema.tables.ItemAliases;
import com.skelril.skree.db.schema.tables.ItemId;
import com.skelril.skree.db.schema.tables.ItemValues;
import com.skelril.skree.db.schema.tables.Modifiers;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class McDb extends SchemaImpl {

	private static final long serialVersionUID = -1345320950;

	/**
	 * The reference instance of <code>mc_db</code>
	 */
	public static final McDb MC_DB = new McDb();

	/**
	 * No further instances allowed
	 */
	private McDb() {
		super("mc_db");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			ItemAliases.ITEM_ALIASES,
			ItemId.ITEM_ID,
			ItemValues.ITEM_VALUES,
			Modifiers.MODIFIERS);
	}
}
